// Mocks generated by Mockito 5.4.6 from annotations
// in sms_console/test/sms_send_form_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i13;

import 'package:flutter/material.dart' as _i6;
import 'package:get/get.dart' as _i7;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sms_console/core/services/tenant_service.dart' as _i5;
import 'package:sms_console/features/sms_console/domain/entities/cost_breakdown_entity.dart'
    as _i9;
import 'package:sms_console/features/sms_console/domain/entities/sms_history_entity.dart'
    as _i10;
import 'package:sms_console/features/sms_console/domain/usecases/get_cost_breakdown_usecase.dart'
    as _i3;
import 'package:sms_console/features/sms_console/domain/usecases/get_sms_history_usecase.dart'
    as _i4;
import 'package:sms_console/features/sms_console/domain/usecases/send_sms_usecase.dart'
    as _i2;
import 'package:sms_console/features/sms_console/presentation/controllers/sms_console_controller.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSendSmsUseCase_0 extends _i1.SmartFake
    implements _i2.SendSmsUseCase {
  _FakeSendSmsUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetCostBreakdownUseCase_1 extends _i1.SmartFake
    implements _i3.GetCostBreakdownUseCase {
  _FakeGetCostBreakdownUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSmsHistoryUseCase_2 extends _i1.SmartFake
    implements _i4.GetSmsHistoryUseCase {
  _FakeGetSmsHistoryUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTenantService_3 extends _i1.SmartFake implements _i5.TenantService {
  _FakeTenantService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingController_4 extends _i1.SmartFake
    implements _i6.TextEditingController {
  _FakeTextEditingController_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_5<T extends _i6.State<_i6.StatefulWidget>>
    extends _i1.SmartFake
    implements _i6.GlobalKey<T> {
  _FakeGlobalKey_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_6 extends _i1.SmartFake implements _i7.RxBool {
  _FakeRxBool_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxn_7<T> extends _i1.SmartFake implements _i7.Rxn<T> {
  _FakeRxn_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxnString_8 extends _i1.SmartFake implements _i7.RxnString {
  _FakeRxnString_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_9<E> extends _i1.SmartFake implements _i7.RxList<E> {
  _FakeRxList_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_10<T> extends _i1.SmartFake
    implements _i7.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SmsConsoleController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSmsConsoleController extends _i1.Mock
    implements _i8.SmsConsoleController {
  MockSmsConsoleController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SendSmsUseCase get sendSmsUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#sendSmsUseCase),
            returnValue: _FakeSendSmsUseCase_0(
              this,
              Invocation.getter(#sendSmsUseCase),
            ),
          )
          as _i2.SendSmsUseCase);

  @override
  _i3.GetCostBreakdownUseCase get getCostBreakdownUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getCostBreakdownUseCase),
            returnValue: _FakeGetCostBreakdownUseCase_1(
              this,
              Invocation.getter(#getCostBreakdownUseCase),
            ),
          )
          as _i3.GetCostBreakdownUseCase);

  @override
  _i4.GetSmsHistoryUseCase get getSmsHistoryUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getSmsHistoryUseCase),
            returnValue: _FakeGetSmsHistoryUseCase_2(
              this,
              Invocation.getter(#getSmsHistoryUseCase),
            ),
          )
          as _i4.GetSmsHistoryUseCase);

  @override
  _i5.TenantService get tenantService =>
      (super.noSuchMethod(
            Invocation.getter(#tenantService),
            returnValue: _FakeTenantService_3(
              this,
              Invocation.getter(#tenantService),
            ),
          )
          as _i5.TenantService);

  @override
  _i6.TextEditingController get phoneController =>
      (super.noSuchMethod(
            Invocation.getter(#phoneController),
            returnValue: _FakeTextEditingController_4(
              this,
              Invocation.getter(#phoneController),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get bodyController =>
      (super.noSuchMethod(
            Invocation.getter(#bodyController),
            returnValue: _FakeTextEditingController_4(
              this,
              Invocation.getter(#bodyController),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get tenantController =>
      (super.noSuchMethod(
            Invocation.getter(#tenantController),
            returnValue: _FakeTextEditingController_4(
              this,
              Invocation.getter(#tenantController),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.GlobalKey<_i6.FormState> get formKey =>
      (super.noSuchMethod(
            Invocation.getter(#formKey),
            returnValue: _FakeGlobalKey_5<_i6.FormState>(
              this,
              Invocation.getter(#formKey),
            ),
          )
          as _i6.GlobalKey<_i6.FormState>);

  @override
  _i7.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_6(this, Invocation.getter(#isLoading)),
          )
          as _i7.RxBool);

  @override
  _i7.RxBool get isHistoryLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isHistoryLoading),
            returnValue: _FakeRxBool_6(
              this,
              Invocation.getter(#isHistoryLoading),
            ),
          )
          as _i7.RxBool);

  @override
  _i7.RxBool get isSending =>
      (super.noSuchMethod(
            Invocation.getter(#isSending),
            returnValue: _FakeRxBool_6(this, Invocation.getter(#isSending)),
          )
          as _i7.RxBool);

  @override
  _i7.Rxn<_i9.CostBreakdownEntity> get costBreakdown =>
      (super.noSuchMethod(
            Invocation.getter(#costBreakdown),
            returnValue: _FakeRxn_7<_i9.CostBreakdownEntity>(
              this,
              Invocation.getter(#costBreakdown),
            ),
          )
          as _i7.Rxn<_i9.CostBreakdownEntity>);

  @override
  _i7.RxnString get costBreakdownError =>
      (super.noSuchMethod(
            Invocation.getter(#costBreakdownError),
            returnValue: _FakeRxnString_8(
              this,
              Invocation.getter(#costBreakdownError),
            ),
          )
          as _i7.RxnString);

  @override
  _i7.RxList<_i10.SmsHistoryItemEntity> get historyItems =>
      (super.noSuchMethod(
            Invocation.getter(#historyItems),
            returnValue: _FakeRxList_9<_i10.SmsHistoryItemEntity>(
              this,
              Invocation.getter(#historyItems),
            ),
          )
          as _i7.RxList<_i10.SmsHistoryItemEntity>);

  @override
  _i7.RxnString get historyError =>
      (super.noSuchMethod(
            Invocation.getter(#historyError),
            returnValue: _FakeRxnString_8(
              this,
              Invocation.getter(#historyError),
            ),
          )
          as _i7.RxnString);

  @override
  _i7.RxnString get nextCursor =>
      (super.noSuchMethod(
            Invocation.getter(#nextCursor),
            returnValue: _FakeRxnString_8(this, Invocation.getter(#nextCursor)),
          )
          as _i7.RxnString);

  @override
  set tenantController(_i6.TextEditingController? value) => super.noSuchMethod(
    Invocation.setter(#tenantController, value),
    returnValueForMissingStub: null,
  );

  @override
  _i7.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_10<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i7.InternalFinalCallback<void>);

  @override
  _i7.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_10<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i7.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<void> refreshAll() =>
      (super.noSuchMethod(
            Invocation.method(#refreshAll, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> fetchCostBreakdown() =>
      (super.noSuchMethod(
            Invocation.method(#fetchCostBreakdown, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> fetchHistory({bool? refresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchHistory, [], {#refresh: refresh}),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> sendSms() =>
      (super.noSuchMethod(
            Invocation.method(#sendSms, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void switchTenant(String? newTenantId) => super.noSuchMethod(
    Invocation.method(#switchTenant, [newTenantId]),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListener(_i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i13.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Disposer addListenerId(Object? key, _i12.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i12.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
